---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: #insert type here
  selector: 
    app: gateway
  ports:
    - protocol: TCP
      port: #insert gateway port here
      targetPort: #insert gateway target port here
---
apiVersion: v1
kind: Service
metadata:
  name: math-service
spec:
  selector: 
    app: math-service
  ports:
    - protocol: TCP
      port: #insert gateway port here
      targetPort: #insert gateway target port here
---
apiVersion: v1
kind: Service
metadata:
  name: string-service
spec:
  selector: 
    app: string-service
  ports:
    - protocol: TCP
      port: #insert gateway port here
      targetPort: #insert gateway target port here
